
#use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.moretv.cn/whaley-vr-ios-midware/WVRPodSpecs.git'
source 'https://git.moretv.cn/whaley-vr-ios-lib/WVRPodSpecs.git'

platform :ios, "9.0"
inhibit_all_warnings!

# 如果有库因为忽略警告而编译失败，单独给他设置不忽略警告
# pod 'ReactiveCocoa', '~> 2.1.8', :inhibit_warnings => true

target 'WVRProgram' do
    
    pod 'LKDBHelper',                   '~> 2.4'
    pod 'HMSegmentedControl'
    pod 'CocoaHTTPServer'
    
    pod 'RZDataBinding'
    pod 'ReactiveObjC',                 '~> 3.0.0'
    
    pod 'WVRMediator',                  '~> 0.2.3'
    pod 'WVRUIFrame',                   '~> 0.1.0'
    pod 'WVRImage',                     '~> 1.1.1'
    pod 'WVRCache',                     '~> 0.0.2'
    pod 'WVRNet',                       '~> 0.1.5'
    pod 'WVRNetModel',                  '~> 0.0.3'
    pod 'WVRAppContext',                '~> 0.1.7'
    pod 'WVRBI',                        '~> 0.0.1'
    pod 'WVRPlayer',                    '~> 0.0.1'
    pod 'WVRParser',                    '~> 0.0.3'
    pod 'WVRShare',                     '~> 0.0.3'
    pod 'WVRWidget',                    '~> 0.3.5'
    pod 'WVRUtil',                      '~> 0.0.1'
    pod 'WVRPlayerUI',                  '~> 0.0.2'
    pod 'WVRAPIService',                '~> 0.0.1'
    pod 'WVRHybrid',                    '~> 0.0.3'
    pod 'WVRInteractor',                '~> 0.0.1'

end



