
source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.moretv.cn/whaley-vr-ios-lib/WVRPodSpecs.git'
source 'https://git.moretv.cn/whaley-vr-ios-midware/WVRPodSpecs.git'
source 'https://git.moretv.cn/whaley-vr-ios-biz/WVRPodSpecs.git'
platform :ios, "9.0"


target 'WVRDanmu' do
    
    pod 'WVRAPIService',                '~> 0.0.1'
    pod 'WVRMediator',                  '~> 0.0.8'
    pod 'WVRNet',                       '~> 0.1.6'
    pod 'WVRUtil',                      '~> 0.0.1'
    pod 'WVRAppContext',                '~> 0.1.3'
    pod 'WVRWidget',                    '~> 0.3.3'
    pod 'WVRPlayerUI',                  '~> 0.0.4'
    
end



